#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Setup
          caches:
            - pip
          script:
            - ls
            #- apt-get update && apt-get install python-psycopg2 --yes
            #- pip install -r requirements.txt
            #- python manage.py test


      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            #- pip install flake8
            #- flake8 . --extend-exclude=dist,build --show-source --statistics
            - ls


  branches:
    feature/pre_release:

    - step:
        name: Make container
        deployment: test
        services:
          - docker
        script:
          - docker login -u $docker_hub_id -p $docker_hub_password
          - docker build -t 000112233/osint_main_repo:ocs_rest -f Dockerfile .
          - docker push 000112233/osint_main_repo:ocs_rest
          - docker logout
