"""
Django settings for OCS_Rest project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from core_management.ftp_upload import FtpFileTransfer

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hwh3ju4-79katalofuzhj6!-v+fiv76bciwfx1bwb(q2q47gvd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# Production
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ESS API Configurations Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

MC_IP = '192.168.18.232'
ESS_IP = '192.168.18.19'
ES_IP = ''
BDS_IP = ''
ESS_SERVER_PORT = '8001'
ESS_SERVER_USER = 'rapidev'
ESS_SERVER_PASSWORD = 'rapidev'
ESS_SERVER_BASE_URL = 'http://{0}:{1}/'.format(ESS_IP,
                                               ESS_SERVER_PORT)
# ip of the serve or its url

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ESS API Configurations End >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ESS API Configurations Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

AIS_IP = '192.168.18.13'
AIS_SERVER_PORT = '5000'
AIS_SERVER_USER = 'rapics'
AIS_SERVER_PASSWORD = 'rapics'
AIS_SERVER_BASE_URL = 'http://{0}:{1}/'.format(AIS_IP, AIS_SERVER_PORT)  # ip of the serve or its url

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ESS API Configurations End >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< FTP CONFIG >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FILE_SERVER = '192.168.18.33'
USERNAME = 'microcrawler'
PASSWORD = 'rapidev'
PORT = 21
MEDIA_SERVER_BASE_PATH = 'http://{0}/osint_system/media_files'.format(FILE_SERVER)
FTP_LOCAL_DIRECTORY = str(Path.home())
if DEBUG:
    MEDIA_URL = MEDIA_SERVER_BASE_PATH + '/media_files/'
else:
    MEDIA_URL = MEDIA_SERVER_BASE_PATH + '/media_files/'
MEDIA_ROOT = '/var/www/html/osint_system/media_files/'

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< FTP CONFIG >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CELERY_BROKER_URL = 'amqp://ocs_broker:rapidev@192.168.18.27/v_ocs_broker'
CELERY_RESULT_BACKEND = ''
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Karachi'

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< API Configurations End >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ElasticSearch Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

CLUSTER_IP = '192.168.18.155'
PORT_ES = '9200'
USERNAME_ES = 'elastic'
PASSWORD_ES = 'uLTpJqxVihdXTIH7vXKO'
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ElasticSearch Configuration End >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< BDS Controller Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>

BDS_SPARK_IP = 'livy.rapidev.ae'
BDS_PORT = '8999'
BDS_USERNAME = 'rapidev'
BDS_PASSWORD = 'root'


# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< BDS Controller Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>

USERNAME_CONSUMER = 'ocs'
PASSWORD_CONSUMER = 'rapidev'
HOST_CONSUMER = '192.168.18.27'

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< BDS Kibana Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< BDS Kibana Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>>

KIBANA_IP = '192.168.18.155'
KIBANA_PORT = '5601'
# BDS_USERNAME = 'rapidev'
# BDS_PASSWORD = 'root'


# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< BDS Controller Configuration End >>>>>>>>>>>>>>>>>>>>>>>>>>>>


# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< HDFS Controller Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>
HDFS_HOST = '192.168.18.182'
HDFS_PORT = '50070'
HDFS_USERNAME = 'daniel'
HDFS_PASSWORD = 'daniel123'
HDFS_ROOT_PATH = 'user/Osint'
HDFS_ROOT_PATH2 = 'user/automl'
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< HDFS Controller Configuration End >>>>>>>>>>>>>>>>>>>>>>>>>>>>
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< YARN JOBS Configuration Start >>>>>>>>>>>>>>>>>>>>>>>>>>>
YARN_IP = "192.168.18.182"
YARN_PORT = "8088"


# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< YARN JOBS Controller Configuration END >>>>>>>>>>>>>>>>>>>>>>>>>>>



# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< SDS Controller >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

SDS_IP = '192.168.18.13'
SDS_PORT = '5000'
SDS_USERNAME = 'rapics'
SDS_PASSWORD = 'rapics'
SDS_SERVER_BASE_URL = 'http://{0}:{1}/'.format(SDS_IP,
                                               SDS_PORT)
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< SDS Controller >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'target_management.apps.TargetManagementConfig',
    'keybase_management.apps.KeybaseManagementConfig',
    'case_management.apps.CaseManagementConfig',
    'report_management.apps.ReportManagementConfig',
    'portfolio_management.apps.PortfolioManagementConfig',
    'account_management.apps.AccountManagementConfig',
    'core_management.apps.CoreManagementConfig',
    'bi_tools.apps.BiToolsConfig',
    'avatar_management.apps.AvatarManagementConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'gm2m',
    'corsheaders',
    'debug_toolbar',
    # 'channels',
    'django_extensions',
    # 'django_filters',
    # 'channels',
    # 'django_eventstream',
    'rest_framework_swagger',
]

MIDDLEWARE = [
    'django_grip.GripMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
    'core_management.middleware.log_middleware',

]
ROOT_URLCONF = 'OCS_Rest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OCS_Rest.wsgi.application'
# ASGI_APPLICATION = 'OCS_Rest.routing.application'
# ASGI_APPLICATION = 'OCS_Rest.asgi.application'
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'osint_db',  # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': 'rapidev',
        'PASSWORD': '1234',
        'HOST': '192.168.18.107',
        # Empty for localhost through domain sockets or
        # '127.0.0.1' for localhost through TCP.
        'PORT': '5432',  # Set to empty string for default.
    }
}

# AUTH_USER_MODEL = ''

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    # 'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema' ,
    'PAGE_SIZE': 10
}

# CORS_ORIGIN_WHITELIST = [
#     'http://localhost:3000',
#     'http://localhost:3001',
#     'http://localhost:3002',
#     'http://192.168.18.118:3000',
#     'http://192.168.18.204:3000',
#     'http://192.168.18.208:3000',
#     'http://0.0.0.0:3000',
# ]
# CORS_ORIGIN_REGEX_WHITELIST = [
#     'http://localhost:3000',
#     'http://localhost:3001',
#     'http://localhost:3002',
#     'http://192.168.18.118:3000',
#     'http://192.168.18.208:3000',
#     'http://192.168.18.204:3000',
#     'http://0.0.0.0:3000',
# ]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.'
                'auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.'
                'password_validation.NumericPasswordValidator',
    },
]
# CHANNEL_LAYERS = {
#      "default": {
#          "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
#          "CONFIG": {
#             "host": "amqp://ocs_broker:rapidev@192.168.18.27/v_ocs_broker",
#         },
#       },
#   }
# GRIP_URL = os.environ.get('GRIP_URL')
# EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.DjangoModelStorage'
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Etc/GMT-5'
#their is an error in this project when it comes to time . 
#Gmt is basically a time standard (0:00) set according to uk time .In order for us to get time according to our time zone we add 'etc/gmt-5' thats how we get our time .


# USE_I18N = True

# USE_L10N = True

# USE_TZ = True


# timezone = 'Asia/Karachi'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

INTERNAL_IPS = [
    '192.168.18.232',
]
